(function(){
var DATA=null, ROUTES=[], STOPS={};
var qEl=null, formEl=null, goEl=null, suggestEl=null, hintEl=null, resultEl=null, diagEl=null;
var nameIndex=null, lastValue='';
function id(x){return document.getElementById(x);} 
function has(o,k){return Object.prototype.hasOwnProperty.call(o,k);} 
function trim(s){return String(s==null?'':s).replace(/^\s+|\s+$/g,'');}
function digits(s){return String(s==null?'':s).replace(/[^0-9]/g,'');}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function fmt(n){n=Number(n)||0;try{return n.toLocaleString('tr-TR');}catch(e){return String(n);}}
function fold(s){s=String(s||'').toLowerCase();var out='',i,ch,map={'ı':'i','ğ':'g','ü':'u','ş':'s','ö':'o','ç':'c','â':'a','î':'i','û':'u','İ':'i','I':'i','Ğ':'g','Ü':'u','Ş':'s','Ö':'o','Ç':'c','Â':'a','Î':'i','Û':'u'};for(i=0;i<s.length;i++){ch=s.charAt(i);out+=map[ch]||ch;}return out;}
function setErr(msg){if(diagEl){diagEl.className='diag err';diagEl.innerHTML=msg;}}
function hideErr(){if(diagEl){diagEl.className='diag';diagEl.innerHTML='';}}
function addEvent(el,t,fn){if(!el)return;if(el.addEventListener){el.addEventListener(t,fn,false);}else if(el.attachEvent){el.attachEvent('on'+t,fn);}}
function stop(e){if(e&&e.preventDefault)e.preventDefault();if(e)e.returnValue=false;return false;}
function showError(title,msg){if(resultEl){resultEl.className='state error';resultEl.innerHTML='<h2>'+esc(title)+'</h2><p>'+esc(msg)+'</p>';}}
function showEmpty(title,msg){if(resultEl){resultEl.className='state';resultEl.innerHTML='<h2>'+esc(title)+'</h2><p>'+esc(msg)+'</p>';}}
function cmp(a,b){a=String(a);b=String(b);return a<b?-1:(a>b?1:0);} 
function dirName(y){return y==='G'?'Gidiş':(y==='D'?'Dönüş':y);} 
function dirClass(y){return y==='G'?'g':(y==='D'?'d':'x');}
function buildNameIndex(){var dk,e;if(nameIndex)return;nameIndex=[];for(dk in STOPS){if(has(STOPS,dk)){e=STOPS[dk];nameIndex.push([dk,e[0],fold(e[0])]);}}}
function aggregate(dk){var e=STOPS[dk], idxs, by={}, lines=[], i,r,hat,yon,I,C,P,total,o,k,j,active=[];if(!e)return null;idxs=e[1]||[];for(i=0;i<idxs.length;i++){r=ROUTES[idxs[i]];if(!r)continue;hat=r[1];yon=r[2];I=Number(r[3])||0;C=Number(r[4])||0;P=Number(r[5])||0;total=I+C+P;o=by[hat];if(!o){o=by[hat]={hat:hat,gz:[],I:0,C:0,P:0,total:0,gzActive:0};}o.gz.push({gz:r[0],yon:yon,I:I,C:C,P:P,total:total});o.I+=I;o.C+=C;o.P+=P;o.total+=total;if(total>0)o.gzActive+=1;}for(k in by){if(has(by,k)){o=by[k];o.gz.sort(function(a,b){return (b.total-a.total)||cmp(a.gz,b.gz);});lines.push(o);}}lines.sort(function(a,b){return (b.total-a.total)||cmp(a.hat,b.hat);});var sumI=0,sumC=0,sumP=0,activeGz=0;for(j=0;j<lines.length;j++){if(lines[j].total>0){active.push(lines[j]);sumI+=lines[j].I;sumC+=lines[j].C;sumP+=lines[j].P;activeGz+=lines[j].gzActive;}}return {dk:dk,name:e[0],active:active,all:lines,sumI:sumI,sumC:sumC,sumP:sumP,activeGz:activeGz};}
function tcell(label,val,extra){return '<div class="tcell '+(extra||'')+'"><div class="tl">'+label+'</div><div class="tv">'+fmt(val)+'</div></div>';}
function renderStop(dk){var a=aggregate(dk),h='',i,l,j,g;if(!a){showError('Durak bulunamadı','Bu kod veri setinde yok: '+dk);return;}if(!a.active.length){showEmpty('Sefer bulunamadı',dk+' · '+a.name+' için aktif sefer eşleşmesi yok.');hintEl.innerHTML='<b>'+esc(dk)+'</b> durağı bulundu, aktif sefer görünmüyor.';hideSuggest();return;}h+='<section class="stop-head"><div class="eyebrow">Durak</div><div class="code">'+esc(a.dk)+'</div><div class="name">'+esc(a.name)+'</div><div class="summary"><div class="sumcell"><div class="l">Hat</div><div class="v">'+fmt(a.active.length)+'</div></div><div class="sumcell"><div class="l">Güzergah</div><div class="v">'+fmt(a.activeGz)+'</div></div><div class="sumcell"><div class="l">Haftaiçi</div><div class="v">'+fmt(a.sumI)+'</div></div><div class="sumcell"><div class="l">Cmt</div><div class="v">'+fmt(a.sumC)+'</div></div><div class="sumcell"><div class="l">Pazar</div><div class="v">'+fmt(a.sumP)+'</div></div></div></section>';
h+='<div class="seclabel"><span>Geçen hatlar</span><span class="ln"></span><span>'+fmt(a.active.length)+'</span></div><div class="lines">';
for(i=0;i<a.active.length;i++){l=a.active[i];h+='<details class="line"><summary class="line-row"><div class="bullet">'+esc(l.hat)+'</div><div class="line-mid"><div><b>'+esc(l.hat)+'</b></div><div class="gzcount">'+fmt(l.gzActive)+' aktif güzergah</div></div><div class="tally">'+tcell('H.İçi',l.I,'h')+tcell('Cmt',l.C)+tcell('Paz',l.P)+'</div></summary><div class="drawer"><div class="gz-head"><div class="c-code">Güzergah kodu</div><div class="c-num">H.İçi</div><div class="c-num">Cmt</div><div class="c-num">Paz</div></div>';for(j=0;j<l.gz.length;j++){g=l.gz[j];if(g.total<=0)continue;h+='<div class="gz"><div class="gzcode">'+esc(g.gz)+' <span class="dir '+dirClass(g.yon)+'">'+dirName(g.yon)+'</span></div><div class="n">'+fmt(g.I)+'</div><div class="n">'+fmt(g.C)+'</div><div class="n">'+fmt(g.P)+'</div></div>';}h+='</div></details>';}
h+='</div>';resultEl.className='';resultEl.innerHTML=h;hintEl.innerHTML='<b>'+esc(a.dk)+'</b> sonucu gösteriliyor.';hideSuggest();try{window.location.hash='durak-'+a.dk;}catch(e){}try{qEl.blur();}catch(e){} }
function hideSuggest(){if(suggestEl){suggestEl.style.display='none';suggestEl.innerHTML='';}}
function renderSuggest(items){var h='<div class="head">Eşleşen duraklar</div>',i;if(!items.length){hideSuggest();return;}for(i=0;i<items.length;i++){h+='<button class="sbtn" type="button" data-code="'+esc(items[i][0])+'"><span class="scode">'+esc(items[i][0])+'</span><span class="sname">'+esc(items[i][1])+'</span></button>';}suggestEl.innerHTML=h;suggestEl.style.display='block';}
function findSuggestions(q){var out=[],dk,fq,i,row,seen={};if(!q)return out;buildNameIndex();if(/^\d+$/.test(q)){for(dk in STOPS){if(has(STOPS,dk)&&dk.indexOf(q)===0){out.push([dk,STOPS[dk][0]]);seen[dk]=1;if(out.length>=20)return out;}}}fq=fold(q);if(fq.length>=2){for(i=0;i<nameIndex.length;i++){row=nameIndex[i];if(!seen[row[0]]&&row[2].indexOf(fq)>=0){out.push([row[0],row[1]]);seen[row[0]]=1;if(out.length>=20)return out;}}}return out;}
function runSearch(raw,fromButton){var q=trim(raw);var code=digits(q);if(code&&has(STOPS,code)){renderStop(code);return;}if(fromButton){if(code){showError('Durak bulunamadı','Bu kod veri setinde yok: '+code);}else{showError('Geçerli bir arama yazın','Durak kodu veya durak adı girin.');}}else{renderSuggest(findSuggestions(q));if(!q){showEmpty('Sorgu bekleniyor','Durak kodunu yazınca sonuç otomatik gelir.');hintEl.innerHTML='Örnek: 322001 yazıp Sorgula’ya basın.';}}}
function onInput(){var v=qEl?qEl.value:'';if(v===lastValue)return;lastValue=v;runSearch(v,false);} 
function bindSuggest(){addEvent(suggestEl,'click',function(e){e=e||window.event;var t=e.target||e.srcElement;while(t&&t!==suggestEl&&String(t.className).indexOf('sbtn')<0){t=t.parentNode;}if(t&&t!==suggestEl){var c=t.getAttribute('data-code');qEl.value=c;lastValue=c;renderStop(c);stop(e);}});}
function selfTest(){var a=aggregate('322001');return !!(a&&a.active.length>0&&a.sumI>0);} 
function boot(){qEl=id('q');formEl=id('searchform');goEl=id('go');suggestEl=id('suggest');hintEl=id('hint');resultEl=id('result');diagEl=id('diag');try{DATA=window.DURAK_DATA||null;ROUTES=DATA&&DATA.routes?DATA.routes:[];STOPS=DATA&&DATA.stops?DATA.stops:{};if(!ROUTES.length||!STOPS['322001']){setErr('Veri yüklenemedi. data.js dosyası index.html ile aynı klasörde olmalı.');showError('Veri yüklenmedi','data.js okunamadı veya eksik.');return;}if(!selfTest()){setErr('Veri okundu ama kontrol testi beklenen sonucu vermedi.');showError('Self-test başarısız','Veri dosyası bozulmuş olabilir.');return;}hideErr();addEvent(formEl,'submit',function(e){runSearch(qEl.value,true);return stop(e);});addEvent(goEl,'click',function(e){runSearch(qEl.value,true);return stop(e);});addEvent(qEl,'input',onInput);addEvent(qEl,'keyup',onInput);addEvent(qEl,'change',onInput);addEvent(qEl,'search',onInput);addEvent(qEl,'paste',function(){setTimeout(onInput,60);});bindSuggest();setInterval(onInput,650);try{var h=String(window.location.hash||'');if(h.indexOf('#durak-')===0){var c=digits(h);if(c&&STOPS[c]){qEl.value=c;lastValue=c;renderStop(c);}}}catch(x){} }catch(err){setErr('JavaScript hatası: '+esc(err&&err.message?err.message:String(err)));showError('JavaScript hatası',err&&err.message?err.message:String(err));}}
if(document.readyState==='loading'){addEvent(document,'DOMContentLoaded',boot);}else{boot();}
})();
